class SnowflakeInfo:
    ANIMAL = 'ANIMAL'
    USERNAME = 'ANIMAL'
    PASSWORD = 'SNOWFLAKE-PASSWORD'
    ACCOUNT = 'SNOWFLAKE-ACCOUNT'
    DATABASE = f'{ANIMAL}_DB'   # DO NOT CHANGE   
    SCHEMA = 'RATE_MY_CLASS'    # DO NOT CHANGE
